# Generated by Django 5.2.1 on 2025-05-31 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlobPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photoTitle', models.CharField(max_length=2000)),
                ('photo', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BlobVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=2000)),
                ('video', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
