# Generated by Django 5.2.1 on 2025-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_blobphoto_created_at_blobvideo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobphoto',
            name='photoTitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blobvideo',
            name='videoTitle',
            field=models.TextField(),
        ),
    ]
