# Generated by Django 4.2 on 2025-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_alter_blobphoto_phototitle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blobphoto',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='blobvideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blobphoto',
            name='photoTitle',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='blobvideo',
            name='videoTitle',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='blobphoto',
            index=models.Index(fields=['created_at'], name='blob_blobph_created_d54709_idx'),
        ),
        migrations.AddIndex(
            model_name='blobphoto',
            index=models.Index(fields=['photoTitle'], name='blob_blobph_photoTi_9284c7_idx'),
        ),
        migrations.AddIndex(
            model_name='blobvideo',
            index=models.Index(fields=['created_at'], name='blob_blobvi_created_967226_idx'),
        ),
        migrations.AddIndex(
            model_name='blobvideo',
            index=models.Index(fields=['videoTitle'], name='blob_blobvi_videoTi_5686be_idx'),
        ),
    ]
