# Generated by Django 5.2.1 on 2025-05-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owned_by',
            field=models.CharField(max_length=500),
        ),
    ]
