# Generated by Django 5.2.1 on 2025-05-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_owned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logo',
        ),
    ]
