# Generated by Django 5.2.1 on 2025-06-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owned_by',
            field=models.CharField(max_length=500),
        ),
    ]
